# Generated by Django 5.1.7 on 2025-04-05 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_interest', models.CharField(max_length=200)),
                ('hobbies_passions', models.TextField()),
                ('join_reason', models.TextField()),
                ('contribution_method', models.TextField()),
                ('member_goals', models.TextField()),
                ('participation_frequency', models.TextField()),
                ('accessibility_needs', models.TextField(blank=True, null=True)),
                ('wants_newsletter', models.BooleanField()),
                ('passionate_causes', models.TextField()),
                ('event_ideas', models.TextField()),
                ('previous_projects', models.TextField()),
                ('six_month_contribution', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('membership_type', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
